# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b5f603ac713c3b72bfdb48ae0d36f57b932c99fa7475fbba43387a3eb70b53725ac4a19b76e36890277a18501ff7cbd254c3ebee6a29ae22d6e60a2178ff2b

test:
  secret_key_base: 8990e47b37d0bbb92c99be8b5176ba3c20380256036194195e5b725748fc6914bc777c0a67a7c611216d9417d3f501827f88cd1ae6a20a176dae24d94c76cbb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
